sn32: 2xx: USB: fix packet drops
SonixQMK/ChibiOS-Contrib pull request #44
Opened 2022-05-01 13:20 UTC by dexter93

This typo was causing packet drops on write after ~100k

fixes OpenRGB support

2022-05-02 12:22 UTC, susch19 requested changes

2022-05-02 12:22 UTC, susch19 commented on os/hal/ports/SN32/LLD/SN32F2xx/USB/hal_usb_lld.c
> +    SN32_USB->INSTSC &= ~(mskEP0_PRESETUP | mskERR_SETUP);
```suggestion
    SN32_USB->INSTSC &= (mskEP0_PRESETUP | mskERR_SETUP);
```

2022-05-02 12:22 UTC, susch19 commented on os/hal/ports/SN32/LLD/SN32F2xx/USB/hal_usb_lld.c
> +    SN32_USB->INSTSC &= ~(mskEP0_PRESETUP | mskERR_SETUP);
Based on the comment above, you shouldn't invert the flags, because then you clear only these two, but you want to keep these two

2022-05-02 15:48 UTC, Jpe230 commented on os/hal/ports/SN32/LLD/SN32F2xx/USB/hal_usb_lld.c
> +    SN32_USB->INSTSC &= ~(mskEP0_PRESETUP | mskERR_SETUP);
According to the datasheet: a logical 1 is a clear bit while logical 0 has no effect. I understand that if you only want to keep those bits you set everything to 1 except those.

2022-05-02 15:54 UTC, Jpe230 commented on os/hal/ports/SN32/LLD/SN32F2xx/USB/hal_usb_lld.c
> +    SN32_USB->INSTSC &= ~(mskEP0_PRESETUP | mskERR_SETUP);
Supporting my comment: Sonix official USB Library sets `SN_USB->INSTC` to `0xFEFBFFFF` which translate to the same operation as @dexter93's implementation.

```
void USB_IRQHandler (void)
{
	uint32_t iwIntFlag;

	//** Get Interrupt Status and clear immediately.
	iwIntFlag = SN_USB->INSTS;
	SN_USB->INSTSC = 0xFEFBFFFF;	//** Don't clear PRESETUP & ERR_SETUP flag
	...
	...
}
```

2022-05-03 08:06 UTC, susch19 commented on os/hal/ports/SN32/LLD/SN32F2xx/USB/hal_usb_lld.c
> +    SN32_USB->INSTSC &= ~(mskEP0_PRESETUP | mskERR_SETUP);
But somehow it stops working, as soon as we clear the ACK and/or NAK Flags. So maybe the issue is somewhere else, but not clearing ACK and NACK seems to be a better workaround for now, than the handleNAK workaround and atleast for me it's stable for now.

2022-05-04 18:57 UTC, dexter93 commented
#45 covers this pretty well. no need for this anymore

2022-05-04 18:57 UTC, closed without merging